#!/usr/bin/env bash
# install-hooks.sh — install Git pre-commit hook that runs clang-format
# Usage: ./scripts/install-hooks.sh

set -euo pipefail

HOOKS_DIR="$(git rev-parse --git-dir)/hooks"
HOOK_FILE="${HOOKS_DIR}/pre-commit"

mkdir -p "${HOOKS_DIR}"

cat > "${HOOK_FILE}" << 'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh
# Checks formatting of staged .c / .h files before committing.

set -euo pipefail

STAGED=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(c|h)$' || true)

if [ -z "${STAGED}" ]; then
    exit 0
fi

if ! command -v clang-format &> /dev/null; then
    echo "Warning: clang-format not found, skipping format check."
    exit 0
fi

UNFORMATTED=""
for file in ${STAGED}; do
    if ! clang-format --dry-run --Werror "${file}" 2>/dev/null; then
        UNFORMATTED="${UNFORMATTED} ${file}"
    fi
done

if [ -n "${UNFORMATTED}" ]; then
    echo ""
    echo "ERROR: The following files are not formatted correctly:"
    for f in ${UNFORMATTED}; do
        echo "  - ${f}"
    done
    echo ""
    echo "Run: make format"
    echo "Then stage the changes and commit again."
    exit 1
fi
EOF

chmod +x "${HOOK_FILE}"
echo "Pre-commit hook installed at: ${HOOK_FILE}"
